name: Quality Assurance

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.2

      - name: Code format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        id: init
        run: |
          git config --global url."https://oauth2:${{ secrets.BOT_GITHUB_TOKEN }}@github.com".insteadOf ssh://git@github.com
          terraform init
        working-directory: test

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: test

      - name: Install tflint
        run: |
          curl -sSLo ${{ env.RUNNER_TEMP}}/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.39.3/tflint_linux_amd64.zip
          unzip ${{ env.RUNNER_TEMP}}/tflint.zip -d ${{ env.RUNNER_TEMP}}
          chmod +x ${{ env.RUNNER_TEMP}}/tflint

      - name: Run tflint
        run: |
          ${{ env.RUNNER_TEMP}}/tflint --init
          ${{ env.RUNNER_TEMP}}/tflint

      - name: Install terraform-docs
        run: |
          curl -sSLo ${{ env.RUNNER_TEMP}}/terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xvzf ${{ env.RUNNER_TEMP}}/terraform-docs.tar.gz -C ${{ env.RUNNER_TEMP}}
          chmod +x ${{ env.RUNNER_TEMP}}/terraform-docs

      - name: Check whether docs should have been updated
        run: |
          ${{ env.RUNNER_TEMP}}/terraform-docs markdown .
          git diff --exit-code README.md
